spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          enabled-predicates:
            - AfterRouteFilterPredicateFactory
            - BeforeRouteFilterPredicateFactory
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            exposeHeaders:
              - Authorization
            allowCredentials: true
            maxAge: 3600

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      hostname: localhost
      port: 8083
      metadata-map:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port}}