spring:
  application:
    name: cart-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      hostname: localhost
      port: 8081
      metadata-map:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port}}